# Generated by Django 2.2.16 on 2020-10-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='list',
            new_name='Lists',
        ),
    ]
