# Generated by Django 2.2.16 on 2020-10-20 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_list_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
    ]
