# Generated by Django 2.2.16 on 2020-10-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=200),
        ),
    ]
